/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame.jdbs;

import database.Database;
import database.table.Column1;
import database.table.Table1;
import fr.AppInfo;
import fr.FrameInfo;
import function.AddFunctions;
import genproject.NetBeansFile;
import java.awt.Color;
import java.awt.Image;
import java.net.URL;
import java.util.Arrays;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIDefaults;
import javax.swing.UIManager;
import main.DaoPattern;
import main.Functions;

/**
 *
 * @author tahir hussain
 */
public class AppBuilder extends javax.swing.JFrame {

    /**
     * Creates new form AppBuilder
     */
    Database database;
    Table1[] unselectedTables;
    Table1[] selectedTables;
    String thisProjPath;
    String newProjPath;
    AppInfo thisAppInfo;
    AppInfo newAppInfo;
    
    public AppBuilder() {
        initComponents();
        //bgLBL.setIcon(getResizedImageIcon(getClass().getResource("/images/tower.jpg")));
    }

    /* public ImageIcon getResizedImageIcon(URL url) {
        ImageIcon icon = new ImageIcon(url);
        Image image = icon.getImage();
        System.out.println(bgLBL.getWidth() + "  " + bgLBL.getHeight());
        image = image.getScaledInstance(bgLBL.getWidth(), bgLBL.getHeight(), Image.SCALE_DEFAULT);
        icon.setImage(image);
        return icon;
    }
     */ 
      
public AppBuilder(AppInfo thisAppInfo,AppInfo newAppInfo,Table1[] unselectedTables, Table1[] selectedTables) {
        this.thisAppInfo = thisAppInfo;
        this.newAppInfo = newAppInfo;
        
        this.unselectedTables = unselectedTables;
        this.selectedTables = selectedTables;
        database = new Database(newAppInfo.getAppTitle(), selectedTables);
        initComponents();
        projectNameLBL.setText(newAppInfo.getAppTitle());
        database=new Database(newAppInfo.getDbName(),selectedTables);
        
        setTableInfo();
    }

    public void setTableInfo() {

        StringBuffer sb = new StringBuffer();
        int counter = 1;
        for (Table1 table : selectedTables) {
            sb.append(String.format(" " + (counter++) + ". " + table.getTableName() + "\n"));
            int count = 1;
            for (Column1 column : table.getColumn()) {
                sb.append(String.format(" \t" + (count++) + ". " + column.getColName() + " \n"));
            }
        }

        tableTxt.setText(sb.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        createBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        projectPathLBL = new javax.swing.JLabel();
        backBtn1 = new javax.swing.JButton();
        projectNameLBL = new javax.swing.JLabel();
        tableScroll = new javax.swing.JScrollPane();
        tableTxt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1200));
        setMinimumSize(new java.awt.Dimension(900, 700));
        setPreferredSize(new java.awt.Dimension(1920, 1200));
        setSize(new java.awt.Dimension(1920, 1200));

        jScrollPane1.setMaximumSize(new java.awt.Dimension(1920, 1200));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(900, 700));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1920, 1200));

        jPanel1.setBackground(new java.awt.Color(53, 59, 72));
        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1200));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1200));

        backBtn.setBackground(new java.awt.Color(87, 101, 116));
        backBtn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/newsoftframe/images/back/back (6).png"))); // NOI18N
        backBtn.setText("BACK");
        backBtn.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/newsoftframe/images/back/back (4).png"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(87, 101, 116));
        cancelBtn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/newsoftframe/images/cancel/cancel (3).png"))); // NOI18N
        cancelBtn.setText("CANCEL");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        createBtn.setBackground(new java.awt.Color(87, 101, 116));
        createBtn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        createBtn.setForeground(new java.awt.Color(255, 255, 255));
        createBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/newsoftframe/images/add/java (1).png"))); // NOI18N
        createBtn.setText("CREATE");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("COLUMNS");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TABLES");

        projectPathLBL.setForeground(new java.awt.Color(255, 255, 255));

        backBtn1.setBackground(new java.awt.Color(87, 101, 116));
        backBtn1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        backBtn1.setForeground(new java.awt.Color(255, 255, 255));
        backBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/newsoftframe/images/file/file.png"))); // NOI18N
        backBtn1.setText("CHANGE");
        backBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn1ActionPerformed(evt);
            }
        });

        projectNameLBL.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        projectNameLBL.setForeground(new java.awt.Color(255, 255, 255));
        projectNameLBL.setText("Project Name");

        tableScroll.setOpaque(true);

        tableTxt.setBackground(new java.awt.Color(53, 59, 72));
        tableTxt.setColumns(20);
        tableTxt.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        tableTxt.setForeground(new java.awt.Color(189, 195, 199));
        tableTxt.setRows(5);
        tableScroll.setViewportView(tableTxt);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(projectNameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(74, 74, 74)
                .addComponent(jLabel1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(tableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(projectPathLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(backBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(300, 300, 300)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(projectNameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(tableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(projectPathLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn1ActionPerformed


    }//GEN-LAST:event_backBtn1ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        List<Table1> list = Arrays.asList(selectedTables);
        for (Table1 t : unselectedTables) {
            list.add(t);
        }
        new TableFrame1(new AppInfo(thisProjPath,"JDBS","JDBS"),new AppInfo(newProjPath,database.getDbName(),newAppInfo.getAppTitle()),database).setVisible(true);
                    this.setVisible(false);
                    
    }//GEN-LAST:event_backBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        System.out.println("App Name--->"+newAppInfo.getAppTitle() +" \n Frame List \n ");
        
        for(FrameInfo cr:newAppInfo.getFrameList()){
            System.out.println("Frame Information-->"+cr);
        }
//         database=new Database(newAppInfo.getDbName(),selectedTables);
         
        if (database.getTables() != null) {

            DaoPattern.createDaoPattern(thisAppInfo, newAppInfo, database);
            AddFunctions.addFunction(newAppInfo, database);
           newProjPath=newAppInfo.getPath();
           thisProjPath=thisAppInfo.getPath();
           
         //           C:/Users/tahir hussain/NewProject/JDBS/src/nbfiles                        
           System.out.println("new proj path is:--->"+newProjPath);
            NetBeansFile.copyNetbeansFile(thisAppInfo.getPath()+"/src/nbfiles/", newProjPath, Functions.getJcName(database.getDbName()));
            //C:\Users\tahir hussain\Documents\CrudeProjects\Sakila
            //File newProjectFile=new File("C:/Users/tahir hussain/Documents/JDBC1/Sakila");
        JOptionPane.showMessageDialog(null,newAppInfo.getAppTitle()+" Application has been created");

        } else {
            System.out.println("No tables");
        }

         
        
        
        
    }//GEN-LAST:event_createBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }

        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppBuilder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton backBtn1;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton createBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel projectNameLBL;
    private javax.swing.JLabel projectPathLBL;
    private javax.swing.JScrollPane tableScroll;
    private javax.swing.JTextArea tableTxt;
    // End of variables declaration//GEN-END:variables
}
