/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame.jdbs;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author tahir hussain
 */
public class InformUser extends javax.swing.JFrame {


    
   private String click;
    

   public InformUser() {
        initComponents();
        //cancelLBL2.setVisible(false);//C:\Users\tahir hussain\Documents\DBandJava\CrudSoft\src\frame\crudsoft\InformUser.java
       this.setLocationRelativeTo(null);
//       this.setUndecorated(true); // Remove title bar
//this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
////this.addComponentsToPane(this.getContentPane());
//this.pack();
        
       okLBL.requestFocus(true);
    }

    
    public InformUser(String title,String descr,String descPath,String cancel,String okPath) {
        super("Message");
        initComponents();
        this.setLocationRelativeTo(null);
        setImage(cancel);
        //this.getClass().getClassLoader().getResource("")
        okLBL.requestFocus(true);
        okLBL.setIcon( new ImageIcon(  getClass().getResource(okPath)));
        imgLBL.setIcon(new ImageIcon(  getClass().getResource(descPath)));        
        description.setText(descr);
//        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
//        this.setUndecorated(false);
    }
/**
     * Creates new form InformUser
     */
        public void setImage(String imgPath){
        cancelLBL1.setIcon(new ImageIcon(  getClass().getResource(imgPath)));
        cancelLBL2.setIcon(new ImageIcon(  getClass().getResource(imgPath)));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        okLBL = new javax.swing.JLabel();
        imgLBL = new javax.swing.JLabel();
        cancelLBL1 = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cancelLBL2 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Message");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(53, 59, 72));
        setMinimumSize(new java.awt.Dimension(500, 210));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 210));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(46, 134, 222));
        jPanel1.setMinimumSize(new java.awt.Dimension(480, 150));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 150));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        okLBL.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        okLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/newsoftframe/images/ok/ok.png"))); // NOI18N
        okLBL.setText("OK");
        okLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okLBLMouseClicked(evt);
            }
        });
        jPanel1.add(okLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 102, 110, 40));

        imgLBL.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        imgLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/newsoftframe/images/information/info (3).png"))); // NOI18N
        jPanel1.add(imgLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 65));

        cancelLBL1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        cancelLBL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/newsoftframe/images/cancel/cancel (3).png"))); // NOI18N
        cancelLBL1.setText("CANCEL");
        cancelLBL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelLBL1MouseClicked(evt);
            }
        });
        jPanel1.add(cancelLBL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 95, 133, 52));

        description.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jPanel1.add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 440, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 500, 150));

        jPanel3.setBackground(new java.awt.Color(87, 101, 116));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 150));

        cancelLBL2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/newsoftframe/images/cancel/can.png"))); // NOI18N
        cancelLBL2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelLBL2MouseClicked(evt);
            }
        });

        title.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(cancelLBL2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cancelLBL2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okLBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okLBLMouseClicked
        click="ok";
        this.setVisible(false);
        
    }//GEN-LAST:event_okLBLMouseClicked

    private void cancelLBL1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelLBL1MouseClicked
        click="cancel";
        this.dispose();
    }//GEN-LAST:event_cancelLBL1MouseClicked

    private void cancelLBL2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelLBL2MouseClicked
        click="cancel";
        this.dispose();
        
    }//GEN-LAST:event_cancelLBL2MouseClicked

    public String getClickValue(){
    return click;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cancelLBL1;
    private javax.swing.JLabel cancelLBL2;
    private javax.swing.JLabel description;
    private javax.swing.JLabel imgLBL;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel okLBL;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
