/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame.jdbs;
import java.awt.Color;
 
/**
 *
 * @author tahir hussain
 */
public class JDBs extends javax.swing.JFrame {

    /**
     * Creates new form CrudSoftFrame
     */
        
    public JDBs() {
        initComponents();
       // bgLBL.setIcon(getResizedImageIcon(getClass().getResource("/images/tower.jpg")));
        
    }
 /*
    public JDBs(Database database) {
     this.database=database;
     initComponents();
     //   bgLBL.setIcon(getResizedImageIcon(getClass().getResource("/images/tower.jpg")));
    }
   public Database getDB(){
       return database;
   }
*/
   /* public ImageIcon getResizedImageIcon(URL url){
                ImageIcon icon=new ImageIcon(url);
                Image image=icon.getImage();
                System.out.println(bgLBL.getWidth()+"  "+bgLBL.getHeight());
                image=image.getScaledInstance(bgLBL.getWidth(), bgLBL.getHeight(), Image.SCALE_SMOOTH);
                icon.setImage(image);
                
                return icon;
    }
   */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sqliteLBL = new javax.swing.JLabel();
        mysqlLBL = new javax.swing.JLabel();
        oracleLBL = new javax.swing.JLabel();
        postgrelLBL = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        openItem = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        importMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JDBS");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(53, 59, 72));
        setBounds(new java.awt.Rectangle(10, 10, 1700, 1073));
        setMinimumSize(new java.awt.Dimension(1024, 1024));
        setName("frame"); // NOI18N
        setSize(new java.awt.Dimension(1920, 1200));

        sqliteLBL.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        sqliteLBL.setForeground(new java.awt.Color(255, 255, 255));
        sqliteLBL.setText("SQLite");
        sqliteLBL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sqliteLBLFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                sqliteLBLFocusLost(evt);
            }
        });
        sqliteLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sqliteLBLMouseClicked(evt);
            }
        });

        mysqlLBL.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        mysqlLBL.setForeground(new java.awt.Color(255, 255, 255));
        mysqlLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/newsoftframe/images/add/db (1).png"))); // NOI18N
        mysqlLBL.setText("MySQL");
        mysqlLBL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mysqlLBLFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mysqlLBLFocusLost(evt);
            }
        });
        mysqlLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mysqlLBLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mysqlLBLMouseEntered(evt);
            }
        });

        oracleLBL.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        oracleLBL.setForeground(new java.awt.Color(255, 255, 255));
        oracleLBL.setText("Oracle");
        oracleLBL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                oracleLBLFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                oracleLBLFocusLost(evt);
            }
        });
        oracleLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oracleLBLMouseClicked(evt);
            }
        });

        postgrelLBL.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        postgrelLBL.setForeground(new java.awt.Color(255, 255, 255));
        postgrelLBL.setText("PostgrelSQL");
        postgrelLBL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                postgrelLBLFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                postgrelLBLFocusLost(evt);
            }
        });
        postgrelLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                postgrelLBLMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(53, 59, 72));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 1024));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1200));

        openItem.setMnemonic('f');
        openItem.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        openItem.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        openItem.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        saveAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItemActionPerformed(evt);
            }
        });
        openItem.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        openItem.add(exitMenuItem);

        menuBar.add(openItem);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        importMenuItem.setMnemonic('t');
        importMenuItem.setText("Import");
        importMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(importMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        copyMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        pasteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasteMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        deleteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(mysqlLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(530, 530, 530)
                .addComponent(oracleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(760, 760, 760)
                .addComponent(postgrelLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(sqliteLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(mysqlLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(oracleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(postgrelLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(470, 470, 470)
                .addComponent(sqliteLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void saveAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveAsMenuItemActionPerformed

    private void importMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_importMenuItemActionPerformed

    private void copyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_copyMenuItemActionPerformed

    private void pasteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasteMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pasteMenuItemActionPerformed

    private void deleteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMenuItemActionPerformed

    private void mysqlLBLFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mysqlLBLFocusGained
         mysqlLBL.setForeground(Color.DARK_GRAY);
       
    }//GEN-LAST:event_mysqlLBLFocusGained

    private void mysqlLBLFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mysqlLBLFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_mysqlLBLFocusLost

    private void oracleLBLFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_oracleLBLFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_oracleLBLFocusGained

    private void oracleLBLFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_oracleLBLFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_oracleLBLFocusLost

    private void postgrelLBLFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_postgrelLBLFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_postgrelLBLFocusGained

    private void postgrelLBLFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_postgrelLBLFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_postgrelLBLFocusLost

    private void sqliteLBLFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sqliteLBLFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_sqliteLBLFocusGained

    private void sqliteLBLFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sqliteLBLFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_sqliteLBLFocusLost

    private void mysqlLBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mysqlLBLMouseClicked
        //database=new Database();
        //database.setDBType(DB.MySQL);
       // database.setDriver("com.mysql.jdbc.Driver");
        //new MySQLFrame(this.database).setVisible(true);
        
        new MySQLFrame().setVisible(true);
        
        this.setVisible(false);
          
    }//GEN-LAST:event_mysqlLBLMouseClicked

    private void oracleLBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oracleLBLMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_oracleLBLMouseClicked

    private void postgrelLBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_postgrelLBLMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_postgrelLBLMouseClicked

    private void sqliteLBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sqliteLBLMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sqliteLBLMouseClicked

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed

    }//GEN-LAST:event_openMenuItemActionPerformed

    private void mysqlLBLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mysqlLBLMouseEntered
//         database=new Database();
//        database.setDBType(DB.MySQL);
//        new MySQLFrame(this.database).setVisible(true);
//       setVisible(false);
    }//GEN-LAST:event_mysqlLBLMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDBs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDBs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDBs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDBs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
/*try{
        //Class.forName("com.jtatto");
         com.jtattoo.plaf.acryl.AcrylLookAndFeel.setTheme("Gray", "INSERT YOUR LICENSE KEY HERE", "my company");
            
            // select the Look and Feel
            UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
                 
        }catch(ClassNotFoundException e){
            System.out.println(e);
        }catch(InstantiationException e){
            System.out.println(e);
        
        }catch(IllegalAccessException e){
            System.out.println(e);
        
        }catch(UnsupportedLookAndFeelException e){
            System.out.println(e);
        
        }
 */

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JDBs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem importMenuItem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel mysqlLBL;
    private javax.swing.JMenu openItem;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JLabel oracleLBL;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JLabel postgrelLBL;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JLabel sqliteLBL;
    // End of variables declaration//GEN-END:variables

}
