/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import com.toedter.calendar.JDateChooser;
import utility.CheckComponents;
import utility.TableMdf;
/**
 *
 * @author tahir hussain
 */
public class JFrameCode extends javax.swing.JFrame {
JDateChooser dateChooser;
    /**
     * Creates new form JFrameCode
     */
    
public JFrameCode() {
        initComponents();
    obj=new Object[]{text1,text2,date1,date2,date3};
    dateChooser=new JDateChooser();
    System.out.println(text1);
    panel.add(dateChooser,new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, -1, -1));
    
    System.out.println("date:"+dateChooser.getDate());
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        text2 = new javax.swing.JTextField();
        date1 = new org.jdesktop.swingx.JXDatePicker();
        text1 = new javax.swing.JTextField();
        date2 = new org.jdesktop.swingx.JXDatePicker();
        Male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        date3 = new org.jdesktop.swingx.JXDatePicker();
        scrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));
        setMinimumSize(new java.awt.Dimension(1024, 1024));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(204, 204, 204));
        panel.setPreferredSize(new java.awt.Dimension(1024, 700));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        text2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        text2.setForeground(new java.awt.Color(73, 73, 73));
        text2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204))));
        text2.setCaretColor(new java.awt.Color(51, 0, 204));
        text2.setOpaque(true);
        text2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                text2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                text2FocusLost(evt);
            }
        });
        text2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text2ActionPerformed(evt);
            }
        });
        panel.add(text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 210, 50));
        panel.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 210, -1));

        text1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), null, null));
        panel.add(text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 200, 50));
        panel.add(date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 40, 200, -1));

        Male.setText("Male");
        panel.add(Male, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 70, -1));

        female.setText("Female");
        panel.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 90, -1));
        panel.add(date3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 80, 200, -1));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1200, 360));

        scrollPane.setBackground(new java.awt.Color(102, 102, 102));
        scrollPane.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        scrollPane.setForeground(new java.awt.Color(204, 204, 204));
        scrollPane.setAutoscrolls(true);

        table.setBackground(new java.awt.Color(204, 204, 204));
        table.setBorder(null);
        table.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        table.setForeground(new java.awt.Color(153, 153, 153));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"xcjhbj", "sddhjh"},
                {"cxbj", "jhhhb"},
                {"jhbh", "bjb"},
                {"jbhjb", "bjjh"}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        scrollPane.setViewportView(table);

        getContentPane().add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 1212, 370));

        btn.setBackground(new java.awt.Color(102, 102, 102));
        btn.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/newsoftframe/images/back/ (1).png"))); // NOI18N
        btn.setText("INSERT");
        btn.setToolTipText("INSERT");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        getContentPane().add(btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 380, 140, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text2ActionPerformed

    private void text2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text2FocusGained
//        System.out.println(dateChooser.getDate());
//        System.out.println(Male.getText());
//        System.out.println(female.getText());
//        System.out.println(text1.getName());
//
//     

    }//GEN-LAST:event_text2FocusGained

    private void text2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_text2FocusLost

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseClicked

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
       
        //System.out.println(date1.getDate());
        System.out.println("\n============");
        System.out.println("Components:"+CheckComponents.getValues(obj));
        System.out.println("\n===========");
        
    }//GEN-LAST:event_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                 
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCode().setVisible(true);
            }
        });
    }
    
    
    Object[] obj;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Male;
    private javax.swing.JButton btn;
    private org.jdesktop.swingx.JXDatePicker date1;
    private org.jdesktop.swingx.JXDatePicker date2;
    private org.jdesktop.swingx.JXDatePicker date3;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panel;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable table;
    private javax.swing.JTextField text1;
    private javax.swing.JTextField text2;
    // End of variables declaration//GEN-END:variables
}
